apiVersion: apps/v1
kind: Deployment
metadata:
  name: critical-workload
  labels:
    app: critical-workload
    workload-tier: critical
    sla: critical
spec:
  replicas: 3
  selector:
    matchLabels:
      app: critical-workload
  template:
    metadata:
      labels:
        app: critical-workload
        workload-tier: critical
        sla: critical
    spec:
      # Node selection for critical NodePool
      nodeSelector:
        workload-tier: critical
        
      # Tolerations to match critical NodePool taints
      tolerations:
        - key: workload-tier
          operator: Equal
          value: critical
          effect: NoSchedule
          
      # Topology spread constraints for high availability
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: critical-workload
              
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
              name: http
              
          # Guaranteed resources for critical workload
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
              
          # Health checks
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
            
          # Environment variables for identification
          env:
            - name: WORKLOAD_TIER
              value: "critical"
            - name: SLA_LEVEL
              value: "high"
              
      # Priority class for critical workloads
      priorityClassName: system-cluster-critical
      
      # Restart policy
      restartPolicy: Always
      
      # DNS policy
      dnsPolicy: ClusterFirst
---
apiVersion: v1
kind: Service
metadata:
  name: critical-workload-service
  labels:
    app: critical-workload
    workload-tier: critical
spec:
  selector:
    app: critical-workload
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
---