apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: standard-nodepool
  labels:
    workload-tier: standard
spec:
  template:
    metadata:
      labels:
        workload-tier: standard
        node-type: general-purpose
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t3.medium", "t3.large", "m5.large", "m5.xlarge", "t3a.medium", "t3a.large"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: standard-nodeclass
      taints:
        - key: workload-tier
          value: standard
          effect: NoSchedule
      expireAfter: 24h
  limits:
    cpu: 500
    memory: 500Gi
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30s
---